### ISSUE TITLE
m_cached_Underline_Character

### ISSUE THREAD

**Issue by nukadelic** [Caeden117/Curved-UI-Utility#1]
im getting `m_cached_Underline_Character doesnt exists in current context for CurvedTextMeshPro script , TMPro version  :Version 3.0.1 - July 27, 2020

**Comment by Caeden117** [comment]
Alright, I've added some code which should handle the breaking changes in the latest TMP versions. Mind checking again?

**Comment by nukadelic** [comment]
good , curvy UI go brrrrrr
